// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU_U7t3WiPJPIkyXyboeWwTvvJ4oB-Pqc',
    appId: '1:120062673090:web:57293d4c835b09fec2fb5b',
    messagingSenderId: '120062673090',
    projectId: 'shoppinglister-bf179',
    authDomain: 'shoppinglister-bf179.firebaseapp.com',
    storageBucket: 'shoppinglister-bf179.appspot.com',
    measurementId: 'G-HMCXSSELZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Z21R3XQN9h8Xfc8gp0fnpd2eqDzl_As',
    appId: '1:120062673090:android:a5974710ae8b879ec2fb5b',
    messagingSenderId: '120062673090',
    projectId: 'shoppinglister-bf179',
    storageBucket: 'shoppinglister-bf179.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_c6PjVznehG1heVPqPFoTbkk1fyzfVo4',
    appId: '1:120062673090:ios:d0f703aeb16ceed4c2fb5b',
    messagingSenderId: '120062673090',
    projectId: 'shoppinglister-bf179',
    storageBucket: 'shoppinglister-bf179.appspot.com',
    iosClientId: '120062673090-9159oeoblosptiqdmau0ih0n5kb0hrpg.apps.googleusercontent.com',
    iosBundleId: 'com.fclarke.shoppinglister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_c6PjVznehG1heVPqPFoTbkk1fyzfVo4',
    appId: '1:120062673090:ios:f390ca3261803bb1c2fb5b',
    messagingSenderId: '120062673090',
    projectId: 'shoppinglister-bf179',
    storageBucket: 'shoppinglister-bf179.appspot.com',
    iosClientId: '120062673090-aca23s21ng94gbfff34l73boi61o2pnd.apps.googleusercontent.com',
    iosBundleId: 'com.fclarke.shoppinglister.RunnerTests',
  );
}
